version: 2
updates:
  - package-ecosystem: bundler
    directory: /api
    schedule:
      interval: daily
    groups:
      rails:
        patterns:
          - "rails"
          - "action*"
          - "active*"
          - "railties"
    open-pull-requests-limit: 10
  - package-ecosystem: npm
    directory: /web
    schedule:
      interval: daily
    groups:
      storybook:
        patterns:
          - "storybook"
          - "@storybook/*"
          - "eslint-plugin-storybook"
      graphql-codegen:
        patterns:
          - "@graphql-codegen/*"
      vitest:
        patterns:
          - "vitest"
          - "@vitest/*"
      playwright:
        patterns:
          - "playwright"
          - "@playwright/*"
      oxc:
        patterns:
          - "oxlint"
          - "oxfmt"
    open-pull-requests-limit: 10
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
