# Set DATABASE_URL to connect to a different server. Rails merges it into the
# settings of the current environment.
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: realworld_development

test:
  <<: *default
  database: realworld_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
