# frozen_string_literal: true

gem 'action_policy', '~> 0.5.7'
gem 'action_policy-graphql', '~> 0.5.3'
gem 'active_record_doctor', '~> 1.8.0', group: :development
gem 'bootsnap', '>= 1.1.0', require: false
gem 'byebug', '~> 11.1.3', platforms: %i[mri mingw x64_mingw], groups: %i[development test]
gem 'database_cleaner-active_record', '~> 2.0.0', group: :test
gem 'devise', '~> 4.8.0'
gem 'factory_bot_rails', '~> 6.1.0', group: :test
gem 'faker', '~> 2.17.0'
gem 'friendly_id', '~> 5.4.2'
gem 'graphql', '~> 1.12.11'
gem 'jwt', '~> 2.2.3'
gem 'listen', '>= 3.0.5', '< 3.6', group: :development
gem 'pg', '~> 1.2.3'
gem 'puma', '~> 5.3.2'
gem 'rack-cors', '~> 1.1.0'
gem 'rails', '~> 6.1.3'
gem 'rails-erd', '~> 1.6', group: :development
gem 'rspec-rails', '~> 5.0', group: :development
gem 'rubocop', '~> 1.16.0', group: :development, require: false
gem 'shoulda-matchers', '~> 4.5.1', group: :test
gem 'solargraph', '~> 0.40.4', group: :development
gem 'spring', '~> 2.1.1', group: :development
gem 'spring-watcher-listen', '~> 2.0.0', group: :development
gem 'tzinfo-data', '~> 1.2.0', platforms: %i[mingw mswin x64_mingw jruby]

git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '~> 2.7.3'

source 'https://rubygems.org'
