# frozen_string_literal: true

source 'https://rubygems.org'
ruby '4.0.7'

gem 'action_policy'
gem 'action_policy-graphql'
gem 'active_record_doctor', group: :development
gem 'bcrypt'
gem 'bootsnap', require: false
gem 'debug', platforms: %i[mri windows], group: %i[development test], require: 'debug/prelude'
gem 'factory_bot_rails', group: :test
gem 'faker', group: %i[development test]
gem 'friendly_id'
gem 'graphql'
gem 'jwt'
gem 'listen', group: :development
gem 'pg'
gem 'puma'
gem 'rack-cors'
gem 'rails'
gem 'rspec-rails', group: %i[development test]
gem 'rubocop', group: :development, require: false
gem 'rubocop-rails', group: :development, require: false
gem 'rubocop-rspec', group: :development, require: false
gem 'shoulda-matchers', group: :test
gem 'tzinfo-data', platforms: %i[windows jruby]
